//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enciklopedija.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pjesma
    {
        public int ID { get; set; }
        public string Naslov { get; set; }
        public string Napomene { get; set; }
        public Nullable<int> IzvodacID { get; set; }
        public Nullable<int> Glasovi { get; set; }
        public byte[] Datoteka { get; set; }
        public string ContentType { get; set; }
        public string FileName { get; set; }
    
        public virtual Izvodac Izvodac { get; set; }
    }
}
