//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enciklopedija.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zanimljivost
    {
        public int ID { get; set; }
        public string Naslov { get; set; }
        public string Opis { get; set; }
        public string Url { get; set; }
        public string VideoUrl { get; set; }
        public Nullable<int> VideoStart { get; set; }
        public Nullable<int> VideoEnd { get; set; }
        public Nullable<int> ZanrID { get; set; }
        public Nullable<int> Glasovi { get; set; }
    
        public virtual Zanr Zanr { get; set; }
    }
}
